# Generated by Django 5.1.5 on 2025-01-26 19:52

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
