# Generated by Django 5.1.5 on 2025-01-26 20:42

import django.db.models.deletion
import webhook_to_sheet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=webhook_to_sheet.models.generate_random_string, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('triggerEvent', models.CharField(choices=[('NEW_CUSTOMER', 'NEW_CUSTOMER'), ('PAYMENT_FIELD', 'PAYMENT_FIELD'), ('PAYMENT_SUCCESS', 'PAYMENT_SUCCESS')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
