# Generated by Django 5.1.5 on 2025-01-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_to_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='triggerEvent',
            field=models.CharField(choices=[('NEW_CUSTOMER', 'customer.created'), ('PAYMENT_SUCCESS', 'charge.succeeded'), ('PAYMENT_CREATED', 'payment_intent.created')], max_length=20),
        ),
    ]
