# Generated by Django 5.1.5 on 2025-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_to_sheet', '0002_alter_event_triggerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='triggerEvent',
            field=models.CharField(choices=[('customer.created', 'NEW_CUSTOMER'), ('charge.succeeded', 'PAYMENT_SUCCESS'), ('payment_intent.created', 'PAYMENT_CREATED')], max_length=30),
        ),
    ]
