# Generated by Django 5.1.5 on 2025-01-27 07:02

import webhook_to_sheet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_to_sheet', '0003_alter_event_triggerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=webhook_to_sheet.models.generate_random_string, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
